name: Mirror
on:
  schedule:
    - cron: "36 */6 * * *"
  workflow_dispatch:
jobs:
  mirror1:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare https://codeberg.org/dz4k/denizen .
      - run: git push --mirror "https://x:$GITHUB_TOKEN@github.com/dz4k/denizen.git"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
