name: Mirror
on:
  schedule:
    - cron: "36 */6 * * *"
  workflow_dispatch:
jobs:
  mirror-denizen:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare https://codeberg.org/dz4k/denizen denizen
      - run: git push -C denizen --mirror "https://x:$GITHUB_TOKEN@github.com/dz4k/denizen.git"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  mirror-whet:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare https://codeberg.org/dz4k/whet whet
      - run: git push -C whet --mirror "https://x:$GITHUB_TOKEN@github.com/dz4k/whet.git"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  mirror-js4k:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare https://codeberg.org/dz4k/js4k js4k
      - run: git push -C js4k --mirror "https://x:$GITHUB_TOKEN@github.com/dz4k/js4k.git"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
